// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lphzdcofykrsujddobmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwaHpkY29meWtyc3VqZGRvYm11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjg4MjgsImV4cCI6MjA2MjcwNDgyOH0.1JmFbTNcvoslKgldf9Lg3Q6rG6miRgK5Ljexvs4o98c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);